# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06f838fec924294a4f8b3cd1a7059f119c3082d00270bbb9fb00dd2de51a154e1f2e5613ddc201865e0411d3177160e204b5a07ed308859ddff203b4fc5e8087

test:
  secret_key_base: 59fdca535a6ef2b7ca248684632159e664b4eb729a8a61fc09906f54e819e18a7bf6000f8f7198c4878cfd5c0567ee4482e322ad682baa8a46268c83621869c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
